Populated enrollment data
CMSgov/ab2d-contracts pull request #7
Opened 2023-02-14 21:25 UTC by sharshar-sb

AB2D-5349 - Populate enrollment data 

HPMS provides enrollment data (both total enrollment & medicare eligible). This PR pulls that enrollment data and populates the contract object with that information then saves it to the database. When a contract is retrieved, this data is pulled and returned by the API.

This PR adds two columns to the contract database for this information.

2023-02-15 18:27 UTC, sb-dkniesteadt requested changes

2023-02-15 18:27 UTC, sb-dkniesteadt commented on src/main/java/gov/cms/ab2d/contracts/hmsapi/HPMSEnrollment.java
> +        this.enrollmentYear = "" + enrollmentYear;
Can we just use a converter? I don't like the way of conversion. It's doing the same thing plus extra steps/

2023-02-16 15:14 UTC, sb-dkniesteadt approved these changes

2023-02-16 16:16 UTC, sb-keane approved these changes

2023-02-17 18:25 UTC, sb-dkniesteadt commented
Re-approved. Looks good

2023-02-17 18:39 UTC, merged